cd $HOME/openeo-checker && uv run python openeotest.py run --api-url https://openeo.dataspace.copernicus.eu/openeo/1.2 --scenario scenarios/vienna_10km_2018_cdse.json
cd $HOME/openeo-checker && uv run python openeotest.py run --api-url https://openeo.eodc.eu/openeo/1.2.0 --scenario scenarios/vienna_10km_2018_eodc.json
cd $HOME/openeo-checker && uv run python openeotest.py run --api-url https://earthengine.openeo.org/v1.0 --scenario scenarios/vienna_10km_2018_earthengine.json
cd $HOME/openeo-checker && uv run python openeotest.py run --api-url https://openeocloud.vito.be/openeo/1.0.0 --scenario scenarios/vienna_10km_2018_openeo_platform.json
cd $HOME/openeo-checker && uv run python openeotest.py run --api-url https://openeo.vito.be/openeo/1.2 --scenario scenarios/vienna_10km_2018_vito.json
cd $HOME/openeo-checker && uv run python openeotest.py run --api-url https://openeo.dataspace.copernicus.eu/openeo/1.2 --scenario scenarios/vienna_10km_2020_cdse.json
cd $HOME/openeo-checker && uv run python openeotest.py run --api-url https://openeo.eodc.eu/openeo/1.2.0 --scenario scenarios/vienna_10km_2020_eodc.json
cd $HOME/openeo-checker && uv run python openeotest.py run --api-url https://earthengine.openeo.org/v1.0 --scenario scenarios/vienna_10km_2020_earthengine.json
cd $HOME/openeo-checker && uv run python openeotest.py run --api-url https://openeocloud.vito.be/openeo/1.0.0 --scenario scenarios/vienna_10km_2020_openeo_platform.json
cd $HOME/openeo-checker && uv run python openeotest.py run --api-url https://openeo.vito.be/openeo/1.2 --scenario scenarios/vienna_10km_2020_vito.json
cd $HOME/openeo-checker && uv run python openeotest.py run --api-url https://openeo.dataspace.copernicus.eu/openeo/1.2 --scenario scenarios/vienna_10km_2024_cdse.json
cd $HOME/openeo-checker && uv run python openeotest.py run --api-url https://openeo.eodc.eu/openeo/1.2.0 --scenario scenarios/vienna_10km_2024_eodc.json
cd $HOME/openeo-checker && uv run python openeotest.py run --api-url https://earthengine.openeo.org/v1.0 --scenario scenarios/vienna_10km_2024_earthengine.json
cd $HOME/openeo-checker && uv run python openeotest.py run --api-url https://openeocloud.vito.be/openeo/1.0.0 --scenario scenarios/vienna_10km_2024_openeo_platform.json
cd $HOME/openeo-checker && uv run python openeotest.py run --api-url https://openeo.vito.be/openeo/1.2 --scenario scenarios/vienna_10km_2024_vito.json
cd $HOME/openeo-checker && uv run python openeotest.py run --api-url https://openeo.dataspace.copernicus.eu/openeo/1.2 --scenario scenarios/bratislava_10km_2018_cdse.json
cd $HOME/openeo-checker && uv run python openeotest.py run --api-url https://openeo.eodc.eu/openeo/1.2.0 --scenario scenarios/bratislava_10km_2018_eodc.json
cd $HOME/openeo-checker && uv run python openeotest.py run --api-url https://earthengine.openeo.org/v1.0 --scenario scenarios/bratislava_10km_2018_earthengine.json
cd $HOME/openeo-checker && uv run python openeotest.py run --api-url https://openeocloud.vito.be/openeo/1.0.0 --scenario scenarios/bratislava_10km_2018_openeo_platform.json
cd $HOME/openeo-checker && uv run python openeotest.py run --api-url https://openeo.vito.be/openeo/1.2 --scenario scenarios/bratislava_10km_2018_vito.json
cd $HOME/openeo-checker && uv run python openeotest.py run --api-url https://openeo.dataspace.copernicus.eu/openeo/1.2 --scenario scenarios/bratislava_10km_2020_cdse.json
cd $HOME/openeo-checker && uv run python openeotest.py run --api-url https://openeo.eodc.eu/openeo/1.2.0 --scenario scenarios/bratislava_10km_2020_eodc.json
cd $HOME/openeo-checker && uv run python openeotest.py run --api-url https://earthengine.openeo.org/v1.0 --scenario scenarios/bratislava_10km_2020_earthengine.json
cd $HOME/openeo-checker && uv run python openeotest.py run --api-url https://openeocloud.vito.be/openeo/1.0.0 --scenario scenarios/bratislava_10km_2020_openeo_platform.json
cd $HOME/openeo-checker && uv run python openeotest.py run --api-url https://openeo.vito.be/openeo/1.2 --scenario scenarios/bratislava_10km_2020_vito.json
cd $HOME/openeo-checker && uv run python openeotest.py run --api-url https://openeo.dataspace.copernicus.eu/openeo/1.2 --scenario scenarios/bratislava_10km_2024_cdse.json
cd $HOME/openeo-checker && uv run python openeotest.py run --api-url https://openeo.eodc.eu/openeo/1.2.0 --scenario scenarios/bratislava_10km_2024_eodc.json
cd $HOME/openeo-checker && uv run python openeotest.py run --api-url https://earthengine.openeo.org/v1.0 --scenario scenarios/bratislava_10km_2024_earthengine.json
cd $HOME/openeo-checker && uv run python openeotest.py run --api-url https://openeocloud.vito.be/openeo/1.0.0 --scenario scenarios/bratislava_10km_2024_openeo_platform.json
cd $HOME/openeo-checker && uv run python openeotest.py run --api-url https://openeo.vito.be/openeo/1.2 --scenario scenarios/bratislava_10km_2024_vito.json
